name: Android CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: copy properties file
      uses: canastro/copy-file-action@master
      with:
        source: "habitica.properties.example"
        target: "habitica.properties"
    - name: copy resources file
      uses: canastro/copy-file-action@master
      with:
        source: "habitica.resources.example"
        target: "habitica.resources"
    - name: copy google services file
      uses: canastro/copy-file-action@master
      with:
        source: "Habitica/google-services.json.example"
        target: "Habitica/google-services.json"
    - name: Build with Gradle
      run: ./gradlew build
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: copy properties file
      uses: canastro/copy-file-action@master
      with:
        source: "habitica.properties.example"
        target: "habitica.properties"
    - name: copy resources file
      uses: canastro/copy-file-action@master
      with:
        source: "habitica.resources.example"
        target: "habitica.resources"
    - name: copy google services file
      uses: canastro/copy-file-action@master
      with:
        source: "Habitica/google-services.json.example"
        target: "Habitica/google-services.json"
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Ktlint
      run: ./gradlew ktlint
