name: Android CI

on:
  push:
    branches: [ develop, release ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Prepare
      run: ./.github/prepare-workflow
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v2
    - name: Run with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assembleProdDebug -PdisablePreDex

  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Prepare
      run: ./.github/prepare-workflow
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v2
    - name: Run with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: testProdDebugUnitTest

  ui-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Prepare
      run: ./.github/prepare-workflow
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v2
    - name: Run with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: connectedProdDebugAndroid

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Prepare
      run: ./.github/prepare-workflow
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v2
    - name: Run with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: ktlint

  detekt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Prepare
      run: ./.github/prepare-workflow
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v2
    - name: Run with Gradle
      uses: gradle/gradle-build-action@@v2
      with:
        arguments: detekt
    - name: Upload SARIF to Github using the upload-sarif action
      uses: github/codeql-action/upload-sarif@v1
      if: ${{ always() }}
      with:
        sarif_file: build/reports/detekt.sarif
